"""empty message

Revision ID: 3b2be98cc706
Revises: e99c837be9f2
Create Date: 2019-06-10 11:08:44.360187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2be98cc706'
down_revision = 'e99c837be9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('survey_asm', sa.String(length=60), nullable=True))
    op.add_column('cases', sa.Column('survey_ev', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'survey_ev')
    op.drop_column('cases', 'survey_asm')
    # ### end Alembic commands ###
