"""empty message

Revision ID: e99c837be9f2
Revises: 
Create Date: 2019-05-31 15:34:10.457103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99c837be9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('log', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('href', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('ctg', sa.Integer(), nullable=True),
    sa.Column('interval_min', sa.Integer(), nullable=True),
    sa.Column('base_min', sa.Integer(), nullable=True),
    sa.Column('post', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolsets',
    sa.Column('codename', sa.String(length=20), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codename'], ['cases.codename'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('codename', 'link_id')
    )
    op.create_table('userlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('post', sa.String(length=20), nullable=False),
    sa.Column('wxid', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wxid'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userlogs')
    op.drop_table('toolsets')
    op.drop_table('links')
    op.drop_table('cases')
    op.drop_table('admins')
    # ### end Alembic commands ###
